import { z } from "zod";
import {
  DEFAULT_PRIORITY,
  DESCRIPTION_MAX_LENGTH,
  PRIORITIES,
  TITLE_MAX_LENGTH,
} from "@/lib/constants";

const DATE_ONLY_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

function isRealCalendarDate(value: string): boolean {
  if (!DATE_ONLY_PATTERN.test(value)) {
    return false;
  }

  const parsed = new Date(`${value}T00:00:00Z`);

  return (
    !Number.isNaN(parsed.getTime()) &&
    parsed.toISOString().slice(0, 10) === value
  );
}

const optionalDueDateSchema = z.preprocess(
  (value) =>
    value === undefined || value === null || value === "" ? undefined : value,
  z
    .string({ error: "Due date must be a valid date" })
    .refine(isRealCalendarDate, {
      error: "Due date must be a real calendar date in YYYY-MM-DD format",
    })
    .optional(),
);

export const createTaskSchema = z.object({
  title: z
    .string({ error: "Title is required" })
    .trim()
    .min(1, { error: "Title is required" })
    .max(TITLE_MAX_LENGTH, {
      error: `Title must be ${TITLE_MAX_LENGTH} characters or fewer`,
    }),
  description: z
    .string()
    .max(DESCRIPTION_MAX_LENGTH, {
      error: `Description must be ${DESCRIPTION_MAX_LENGTH} characters or fewer`,
    })
    .optional(),
  priority: z
    .enum(PRIORITIES, { error: "Priority must be low, medium, or high" })
    .default(DEFAULT_PRIORITY),
  dueDate: optionalDueDateSchema,
});

export type CreateTaskInput = z.infer<typeof createTaskSchema>;

export type CreateTaskValidationResult =
  | { success: true; data: CreateTaskInput }
  | { success: false; fieldErrors: Record<string, string[]> };

export function validateCreateTaskInput(
  input: unknown,
): CreateTaskValidationResult {
  const result = createTaskSchema.safeParse(input);

  if (result.success) {
    return { success: true, data: result.data };
  }

  return {
    success: false,
    fieldErrors: z.flattenError(result.error).fieldErrors,
  };
}

/**
 * Identifiers are cuid-shaped: the default is generated by Prisma, but the
 * value arrives from the client, so anything outside a plain identifier
 * alphabet is rejected before it reaches the database layer.
 */
const TASK_ID_PATTERN = /^[A-Za-z0-9_-]{1,64}$/;

/**
 * Single definition of the task-id rules, shared by every action that takes a
 * task reference (toggle, delete, update) so the three cannot drift apart.
 */
const taskIdSchema = z
  .string({ error: "Task id is required" })
  .min(1, { error: "Task id is required" })
  .max(64, { error: "Task id is too long" })
  .regex(TASK_ID_PATTERN, { error: "Task id is malformed" });

/**
 * Only the task id and the intended end state are accepted. Status strings,
 * `completedAt` values and every other column are deliberately absent: the
 * server derives the actual database update from `completed` alone.
 */
export const toggleTaskCompletionSchema = z.object({
  taskId: taskIdSchema,
  completed: z.boolean({ error: "Completed must be a boolean" }),
});

export type ToggleTaskCompletionInput = z.infer<
  typeof toggleTaskCompletionSchema
>;

export type ToggleTaskCompletionValidationResult =
  | { success: true; data: ToggleTaskCompletionInput }
  | { success: false; fieldErrors: Record<string, string[]> };

export function validateToggleTaskCompletionInput(
  input: unknown,
): ToggleTaskCompletionValidationResult {
  const result = toggleTaskCompletionSchema.safeParse(input);

  if (result.success) {
    return { success: true, data: result.data };
  }

  return {
    success: false,
    fieldErrors: z.flattenError(result.error).fieldErrors,
  };
}

/**
 * A delete request carries a reference and nothing else. The confirmation
 * happens in the UI, so the server must never be told *which* row to remove by
 * anything the client can influence beyond the id: no title, status, priority,
 * or timestamps.
 *
 * Zod objects strip unknown keys, so a client that also sends `title`,
 * `status` or `completedAt` has them discarded here before the action runs.
 */
export const deleteTaskSchema = z.object({
  taskId: taskIdSchema,
});

export type DeleteTaskInput = z.infer<typeof deleteTaskSchema>;

export type DeleteTaskValidationResult =
  | { success: true; data: DeleteTaskInput }
  | { success: false; fieldErrors: Record<string, string[]> };

export function validateDeleteTaskInput(
  input: unknown,
): DeleteTaskValidationResult {
  const result = deleteTaskSchema.safeParse(input);

  if (result.success) {
    return { success: true, data: result.data };
  }

  return {
    success: false,
    fieldErrors: z.flattenError(result.error).fieldErrors,
  };
}

/**
 * An update carries the task id plus exactly the four editable fields.
 *
 * The field rules are lifted from {@link createTaskSchema} so an edit cannot
 * drift from a create, with one deliberate difference: `priority` is required
 * here instead of defaulting. A defaulted priority would let a client that
 * omitted the field silently reset an existing task to "medium".
 *
 * `status` and `completedAt` are absent by design. `toggleTaskCompletion` is
 * the only writer of completion state, and it derives both values itself, so
 * adding them here would create a second, less safe path to the same state.
 *
 * Zod strips unknown keys, so `id`, `status`, `completedAt`, `createdAt`,
 * `updatedAt`, or a nested `where`/`data` payload sent by a client are dropped
 * here and can never reach the update.
 */
export const updateTaskSchema = createTaskSchema
  .omit({ priority: true })
  .extend({
    taskId: taskIdSchema,
    priority: z.enum(PRIORITIES, {
      error: "Priority must be low, medium, or high",
    }),
  });

export type UpdateTaskInput = z.infer<typeof updateTaskSchema>;

export type UpdateTaskValidationResult =
  | { success: true; data: UpdateTaskInput }
  | { success: false; fieldErrors: Record<string, string[]> };

export function validateUpdateTaskInput(
  input: unknown,
): UpdateTaskValidationResult {
  const result = updateTaskSchema.safeParse(input);

  if (result.success) {
    return { success: true, data: result.data };
  }

  return {
    success: false,
    fieldErrors: z.flattenError(result.error).fieldErrors,
  };
}
